// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// uno_binding.cpp
std::string uno_version();
extern "C" SEXP _Uno_uno_version() {
  BEGIN_CPP11
    return cpp11::as_sexp(uno_version());
  END_CPP11
}
// uno_binding.cpp
cpp11::list uno_solve_impl(int n, cpp11::doubles lb, cpp11::doubles ub, std::string sense, SEXP obj, SEXP grad, int m, cpp11::doubles cl, cpp11::doubles cu, SEXP cons, cpp11::integers jac_rows, cpp11::integers jac_cols, SEXP jac, cpp11::integers hess_rows, cpp11::integers hess_cols, SEXP hess, cpp11::doubles x0, std::string preset, int base_indexing, bool verbose, cpp11::list options, std::string lagrangian_sign, SEXP dual0, SEXP iter_callback, SEXP log_callback);
extern "C" SEXP _Uno_uno_solve_impl(SEXP n, SEXP lb, SEXP ub, SEXP sense, SEXP obj, SEXP grad, SEXP m, SEXP cl, SEXP cu, SEXP cons, SEXP jac_rows, SEXP jac_cols, SEXP jac, SEXP hess_rows, SEXP hess_cols, SEXP hess, SEXP x0, SEXP preset, SEXP base_indexing, SEXP verbose, SEXP options, SEXP lagrangian_sign, SEXP dual0, SEXP iter_callback, SEXP log_callback) {
  BEGIN_CPP11
    return cpp11::as_sexp(uno_solve_impl(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lb), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(ub), cpp11::as_cpp<cpp11::decay_t<std::string>>(sense), cpp11::as_cpp<cpp11::decay_t<SEXP>>(obj), cpp11::as_cpp<cpp11::decay_t<SEXP>>(grad), cpp11::as_cpp<cpp11::decay_t<int>>(m), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(cl), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(cu), cpp11::as_cpp<cpp11::decay_t<SEXP>>(cons), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(jac_rows), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(jac_cols), cpp11::as_cpp<cpp11::decay_t<SEXP>>(jac), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(hess_rows), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(hess_cols), cpp11::as_cpp<cpp11::decay_t<SEXP>>(hess), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x0), cpp11::as_cpp<cpp11::decay_t<std::string>>(preset), cpp11::as_cpp<cpp11::decay_t<int>>(base_indexing), cpp11::as_cpp<cpp11::decay_t<bool>>(verbose), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(options), cpp11::as_cpp<cpp11::decay_t<std::string>>(lagrangian_sign), cpp11::as_cpp<cpp11::decay_t<SEXP>>(dual0), cpp11::as_cpp<cpp11::decay_t<SEXP>>(iter_callback), cpp11::as_cpp<cpp11::decay_t<SEXP>>(log_callback)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_Uno_uno_solve_impl", (DL_FUNC) &_Uno_uno_solve_impl, 25},
    {"_Uno_uno_version",    (DL_FUNC) &_Uno_uno_version,     0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_Uno(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
