# Generated by cpp11: do not edit by hand

uno_version <- function() {
  .Call(`_Uno_uno_version`)
}

uno_solve_impl <- function(n, lb, ub, sense, obj, grad, m, cl, cu, cons, jac_rows, jac_cols, jac, hess_rows, hess_cols, hess, x0, preset, base_indexing, verbose, options, lagrangian_sign, dual0, iter_callback, log_callback) {
  .Call(`_Uno_uno_solve_impl`, n, lb, ub, sense, obj, grad, m, cl, cu, cons, jac_rows, jac_cols, jac, hess_rows, hess_cols, hess, x0, preset, base_indexing, verbose, options, lagrangian_sign, dual0, iter_callback, log_callback)
}
